name: Build And Deploy

on:
  push:
    branches:
      [ "main" ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 22.2.0
              uses: actions/setup-node@v2
              with:
                node-version: '22.2.0'

            - name: Install Dependencies (Client)
              run: |
                cd client
                npm ci
            
            - name: Install Dependencies (Server)
              run: |
                cd server
                npm ci
            

            - name: Build Client
              run: |
                cd client
                npm run build

            - name: Create client .env file
              run: |
                cd client
                echo "${{ secrets.CLIENT_ENV }}" > .env
          
            - name: Create server .env file
              run: |
                cd server
                echo "${{ secrets.SERVER_ENV }}" > .env

            - name: Deploy to DigitalOcean
              env: 
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
                SSH_HOST: ${{ secrets.SSH_HOST }}
              run: |
                mkdir -p ~/.ssh/
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
                ssh -i ~/.ssh/id_rsa $SSH_USERNAME@$SSH_HOST 'echo SSH connection successful'
                rsync -avz --delete-after --quiet client/ $SSH_USERNAME@$SSH_HOST:~/MERN-CICD/client/
                rsync -avz --delete-after --quiet server/ $SSH_USERNAME@$SSH_HOST:~/MERN-CICD/server/
                ssh $SSH_USERNAME@$SSH_HOST '
                    cd ~/MERN-CICD/client &&
                    npm install &&
                    npm run build &&
                    cd ../server &&
                    npm install &&
                    pm2 restart all
                '

